apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: cluster-as-a-service
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      # renovate: datasource=github-releases depName=upbound/configuration-aws-network
      version: "v0.8.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks
      # renovate: datasource=github-releases depName=upbound/configuration-aws-eks
      version: "v0.6.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
      # renovate: datasource=github-releases depName=upbound/configuration-aws-eks-irsa
      version: "v0.4.1"
    - configuration: xpkg.upbound.io/upbound/configuration-gcp-network
      # renovate: datasource=github-releases depName=upbound/configuration-gcp-network
      version: "v0.1.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gcp-gke
      # renovate: datasource=github-releases depName=upbound/configuration-gcp-gke
      version: "v0.1.0"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      # renovate: datasource=github-releases depName=upbound/function-patch-and-transform
      version: "v0.2.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: "v0.10.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: "v0.16.0"
