apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.aws.platform.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: upbound-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: XNetwork
        base:
          apiVersion: aws.platform.upbound.io/v1alpha1
          kind: XNetwork
          spec:
            compositionSelector:
              matchLabels:
                type: basic
            parameters:
              deletionPolicy: Delete
              providerConfigName: default
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.id
            toFieldPath: spec.parameters.id
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.region
            toFieldPath: spec.parameters.region

      - name: XEKS
        base:
          apiVersion: aws.platform.upbound.io/v1alpha1
          kind: XEKS
          spec:
            parameters:
              deletionPolicy: Delete
              providerConfigName: default
              version: "1.28"
        connectionDetails:
          - type: FromConnectionSecretKey
            fromConnectionSecretKey: kubeconfig
            name: kubeconfig
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.id
            toFieldPath: metadata.labels[xeks.aws.platform.upbound.io/cluster-id]
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.id
            toFieldPath: spec.parameters.id
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.region
            toFieldPath: spec.parameters.region
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.id
            toFieldPath: metadata.annotations[crossplane.io/external-name]
          - type: FromCompositeFieldPath
            fromFieldPath: metadata.uid
            toFieldPath: spec.writeConnectionSecretToRef.name
            transforms:
              - type: string
                string:
                  fmt: '%s-eks'
                  type: Format
          - type: FromCompositeFieldPath
            fromFieldPath: spec.writeConnectionSecretToRef.namespace
            toFieldPath: spec.writeConnectionSecretToRef.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.nodes.count
            toFieldPath: spec.parameters.nodes.count
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.nodes.instanceType
            toFieldPath: spec.parameters.nodes.instanceType
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.iam.roleArn
            toFieldPath: spec.parameters.iam.roleArn
          - type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.iam.userArn
            toFieldPath: spec.parameters.iam.userArn
          - type: ToCompositeFieldPath
            fromFieldPath: status.eks
            toFieldPath: status.eks
            policy: 
              fromFieldPath: Required
      - name: usageXEksByArbitraryLabeledRelease
        base:
          apiVersion: apiextensions.crossplane.io/v1alpha1
          kind: Usage
          spec:
            by:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              resourceSelector:
                matchLabels:
                  platform.upbound.io/deletion-ordering: enabled
            of:
              apiVersion: aws.platform.upbound.io/v1alpha1
              kind: XEKS
              resourceSelector:
                matchControllerRef: true
        readinessChecks:
          - type: None
