apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.aws.platform.upbound.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: aws.platform.upbound.io
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  connectionSecretKeys:
    - kubeconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Cluster configuration parameters.
                  properties:
                    id:
                      type: string
                      description: ID of this Cluster that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    iam:
                      type: object
                      description: IAM configuration to connect as ClusterAdmin.
                      properties:
                        roleArn:
                          description: The IAM Role ARN to connect as ClusterAdmin.
                          type: string
                        userArn:
                          description: The IAM User ARN to connect as ClusterAdmin.
                          type: string
                    nodes:
                      type: object
                      description: Cluster node configuration parameters.
                      properties:
                        count:
                          type: integer
                          description: Desired node count, from 1 to 100.
                        instanceType:
                          type: string
                          description: instance types associated with the Node Group.
                          default: t3.small
                      required:
                        - count
                        - instanceType
                  required:
                    - id
                    - nodes
                    - region
              required:
                - parameters
