apiVersion: example.upbound.io/v1alpha1
kind: Space
metadata:
  name: opusdavei-space
spec:
  parameters:
    clusterId: opusdavei-space
    account: crossplane-by-example
    version: "1.1.0"
    host: proxy.upbound.opusdavei.org
    spacesPullSecretRef:
      name: upbound-pull-secret
      namespace: upbound-system
    helmCredentialsSecretRef:
      name: helm-pull-secret
      namespace: upbound-system